
include: "../rules/TSO500_SampleSheet/TSO500_SampleSheet.smk"
include: "../rules/Illumina_TSO500/Illumina_TSO500.smk"
include: "../rules/Illumina_TST170/Illumina_TST170.smk"
include: "../rules/Bcbio/Bcbio.smk"
include: "../rules/ONCOCNV/ONCOCNV.smk"
include: "../rules/cnvkit/cnvkit.smk"
include: "../rules/Arriba/Arriba.smk"
include: "../rules/Imbalance/Imbalance.smk"
include: "../rules/exon_splicing/exon_splicing.smk"
include: "../rules/Collect_results/Collect_results.smk"
